// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AnomalyDetectionEntry struct {
	ParkID       string  `json:"ParkId"`
	TurbineID    string  `json:"TurbineId"`
	Value        float64 `json:"Value"`
	Availability int     `json:"Availability"`
}

type AverageProductionEntry struct {
	ParkID       string  `json:"ParkId"`
	Region       string  `json:"Region"`
	AverageValue float64 `json:"AverageValue"`
	HighestValue float64 `json:"HighestValue"`
	LowestValue  float64 `json:"LowestValue"`
}
